export const CHEER_LIMITS = {
  FREE_DAILY_LIMIT: 3,
  COOLDOWN_HOURS: 24,
  MAX_MESSAGE_LENGTH: 200,
} as const;

export const SUBSCRIPTION_CHEER_LIMITS = {
  FREE: CHEER_LIMITS.FREE_DAILY_LIMIT,
  ACTIVE: null, // 무제한
  EXPIRED: CHEER_LIMITS.FREE_DAILY_LIMIT,
  CANCELLED: CHEER_LIMITS.FREE_DAILY_LIMIT,
} as const;
