export const TODO_CATEGORY_LIMITS = {
  FREE_MAX_COUNT: 3,
  ACTIVE_MAX_COUNT: 30,
} as const;

export const SUBSCRIPTION_TODO_CATEGORY_LIMITS = {
  FREE: TODO_CATEGORY_LIMITS.FREE_MAX_COUNT,
  ACTIVE: TODO_CATEGORY_LIMITS.ACTIVE_MAX_COUNT,
  EXPIRED: TODO_CATEGORY_LIMITS.FREE_MAX_COUNT,
  CANCELLED: TODO_CATEGORY_LIMITS.FREE_MAX_COUNT,
} as const;
