export const TIME_FORMATS = ['TWELVE_HOUR', 'TWENTY_FOUR_HOUR'] as const;

export const USER_PREFERENCE_DEFAULTS = {
  PUSH_ENABLED: false,
  NIGHT_PUSH_ENABLED: false,
  TIMEZONE: 'UTC',
  MORNING_REMINDER_HOUR: 8,
  MORNING_REMINDER_MINUTE: 0,
  EVENING_REMINDER_HOUR: 18,
  EVENING_REMINDER_MINUTE: 0,
  TIME_FORMAT: 'TWELVE_HOUR',
  WEATHER_MORNING_ENABLED: true,
  WEATHER_MORNING_HOUR: 7,
  WEATHER_MORNING_MINUTE: 0,
  WEATHER_EVENING_ENABLED: true,
  WEATHER_EVENING_HOUR: 18,
  WEATHER_EVENING_MINUTE: 0,
} as const;

export const NIGHT_TIME_CONFIG = {
  START_HOUR: 21,
  END_HOUR: 8,
} as const;

export const MORNING_REMINDER_HOUR_RANGE = {
  MIN: 0,
  MAX: 11,
} as const;

export const EVENING_REMINDER_HOUR_RANGE = {
  MIN: 12,
  MAX: 23,
} as const;

export const WEATHER_HOUR_RANGE = {
  MIN: 0,
  MAX: 23,
} as const;
