export const NOTIFICATION_TYPE = {
  FOLLOW_NEW: 'FOLLOW_NEW',
  FOLLOW_ACCEPTED: 'FOLLOW_ACCEPTED',
  NUDGE_RECEIVED: 'NUDGE_RECEIVED',
  CHEER_RECEIVED: 'CHEER_RECEIVED',
  DAILY_COMPLETE: 'DAILY_COMPLETE',
  FRIEND_COMPLETED: 'FRIEND_COMPLETED',
  TODO_REMINDER: 'TODO_REMINDER',
  TODO_SHARED: 'TODO_SHARED',
  MORNING_REMINDER: 'MORNING_REMINDER',
  EVENING_REMINDER: 'EVENING_REMINDER',
  WEEKLY_ACHIEVEMENT: 'WEEKLY_ACHIEVEMENT',
  SYSTEM_NOTICE: 'SYSTEM_NOTICE',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];

export const NOTIFICATION_LIMITS = {
  MAX_FETCH_LIMIT: 50,
  DEFAULT_FETCH_LIMIT: 20,
  MAX_PUSH_TOKEN_LENGTH: 200,
} as const;

export const EXPO_PUSH_TOKEN_REGEX = /^ExponentPushToken\[.+\]$/;
