export const NOTIFICATION_TYPE = {
  FOLLOW_NEW: 'FOLLOW_NEW',
  FOLLOW_ACCEPTED: 'FOLLOW_ACCEPTED',
  NUDGE_RECEIVED: 'NUDGE_RECEIVED',
  CHEER_RECEIVED: 'CHEER_RECEIVED',
  DAILY_COMPLETE: 'DAILY_COMPLETE',
  FRIEND_COMPLETED: 'FRIEND_COMPLETED',
  TODO_REMINDER: 'TODO_REMINDER',
  TODO_SHARED: 'TODO_SHARED',
  MORNING_REMINDER: 'MORNING_REMINDER',
  EVENING_REMINDER: 'EVENING_REMINDER',
  WEEKLY_ACHIEVEMENT: 'WEEKLY_ACHIEVEMENT',
  // AI
  WEEKLY_REPORT: 'WEEKLY_REPORT',
  MONTHLY_REPORT: 'MONTHLY_REPORT',
  AI_SUGGESTION: 'AI_SUGGESTION',
  SYSTEM_NOTICE: 'SYSTEM_NOTICE',
  // 관리자 발송
  ADMIN_BROADCAST: 'ADMIN_BROADCAST',
  ADMIN_TARGETED: 'ADMIN_TARGETED',
  // 리텐션
  WINBACK: 'WINBACK',
  // 소셜 요약
  SOCIAL_DIGEST: 'SOCIAL_DIGEST',
  NUDGE_SUGGEST: 'NUDGE_SUGGEST',
  // 활성 유저 재방문 유도
  LUNCH_NUDGE: 'LUNCH_NUDGE',
  STREAK_AT_RISK: 'STREAK_AT_RISK',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];

export const NOTIFICATION_LIMITS = {
  MAX_FETCH_LIMIT: 50,
  DEFAULT_FETCH_LIMIT: 20,
  MAX_PUSH_TOKEN_LENGTH: 200,
} as const;

export const EXPO_PUSH_TOKEN_REGEX = /^ExponentPushToken\[.+\]$/;

// =========================================================================
// 알림 카테고리
// =========================================================================

export const NOTIFICATION_CATEGORY = {
  ALL: 'ALL',
  NOTICE: 'NOTICE',
  TODO: 'TODO',
  SOCIAL: 'SOCIAL',
} as const;

export type NotificationCategory =
  (typeof NOTIFICATION_CATEGORY)[keyof typeof NOTIFICATION_CATEGORY];

/** 카테고리 → NotificationType[] 매핑 (ALL 제외) */
export const CATEGORY_TYPE_MAP: Record<
  Exclude<NotificationCategory, 'ALL'>,
  readonly NotificationType[]
> = {
  NOTICE: [
    NOTIFICATION_TYPE.SYSTEM_NOTICE,
    NOTIFICATION_TYPE.ADMIN_BROADCAST,
    NOTIFICATION_TYPE.ADMIN_TARGETED,
  ],
  TODO: [
    NOTIFICATION_TYPE.TODO_REMINDER,
    NOTIFICATION_TYPE.TODO_SHARED,
    NOTIFICATION_TYPE.DAILY_COMPLETE,
    NOTIFICATION_TYPE.MORNING_REMINDER,
    NOTIFICATION_TYPE.EVENING_REMINDER,
    NOTIFICATION_TYPE.WEEKLY_ACHIEVEMENT,
    NOTIFICATION_TYPE.WEEKLY_REPORT,
    NOTIFICATION_TYPE.MONTHLY_REPORT,
    NOTIFICATION_TYPE.AI_SUGGESTION,
    NOTIFICATION_TYPE.WINBACK,
    NOTIFICATION_TYPE.LUNCH_NUDGE,
    NOTIFICATION_TYPE.STREAK_AT_RISK,
  ],
  SOCIAL: [
    NOTIFICATION_TYPE.FOLLOW_NEW,
    NOTIFICATION_TYPE.FOLLOW_ACCEPTED,
    NOTIFICATION_TYPE.NUDGE_RECEIVED,
    NOTIFICATION_TYPE.CHEER_RECEIVED,
    NOTIFICATION_TYPE.FRIEND_COMPLETED,
    NOTIFICATION_TYPE.SOCIAL_DIGEST,
    NOTIFICATION_TYPE.NUDGE_SUGGEST,
  ],
} as const;
