export const IdentityLogEvent = {
  USER_REGISTERED: "identity.user.registered",
  EMAIL_VERIFIED: "identity.email.verified",
  VERIFICATION_RESENT: "identity.verification.resent",
  USER_LOGGED_IN: "identity.user.logged-in",
  PROFILE_UPDATED: "identity.profile.updated",
  PASSWORD_RESET_REQUESTED: "identity.password-reset.requested",
  PASSWORD_RESET_REQUEST_SKIPPED: "identity.password-reset.request.skipped",
  PASSWORD_RESET_COMPLETED: "identity.password-reset.completed",
  PASSWORD_CHANGED: "identity.password.changed",
  PASSWORD_SET: "identity.password.set",
  PASSWORD_REHASHED: "identity.password.rehashed",
  PASSWORD_REHASH_FAILED: "identity.password.rehash.failed",
  VERIFICATION_CREATED: "identity.verification.created",
  VERIFICATION_FAILED: "identity.verification.failed",
  VERIFICATION_CONSUMED: "identity.verification.consumed",

  ACCOUNT_DELETION_REQUESTED: "identity.account.deletion-requested",
  ACCOUNT_RESTORED: "identity.account.restored",
  ACCOUNT_PURGED: "identity.account-purge.user.completed",
  ACCOUNT_PURGE_FAILED: "identity.account-purge.user.failed",
  ACCOUNT_PURGE_SETTLEMENT_FAILED: "identity.account-purge.settlement.failed",
  ACCOUNT_PURGE_COMPLETED: "identity.account-purge.completed",
  ACCOUNT_PURGE_SCHEDULER_REGISTERED: "identity.account-purge.scheduler.registered",
  ACCOUNT_PURGE_CATCH_UP_DISPATCHED: "identity.account-purge.catch-up.dispatched",
  ACCOUNT_PURGE_JOB_STARTED: "identity.account-purge.job.started",
  ACCOUNT_PURGE_JOB_FAILED: "identity.account-purge.job.failed",
  SESSION_LOGGED_OUT: "identity.session.logged-out",
  ALL_SESSIONS_LOGGED_OUT: "identity.session.all-logged-out",
  SESSION_REVOKED: "identity.session.revoked",
  SESSION_TOKENS_REFRESHED: "identity.session.tokens-refreshed",
  SESSION_ROTATION_CONFLICT: "identity.session.rotation.conflict",
  SESSION_TOKEN_REUSE_DETECTED: "identity.session.token-reuse.detected",
  VERIFICATION_EMAIL_FAILED: "identity.verification.email.failed",
  OAUTH_REDIRECT_REJECTED: "identity.oauth.redirect.rejected",
  OAUTH_STATE_REJECTED: "identity.oauth.state.rejected",
  OAUTH_EXCHANGE_REJECTED: "identity.oauth.exchange.rejected",
} as const;
