export const TODO_CATEGORY_LIMITS = {
  FREE_MAX_COUNT: 3,
} as const;

export const SUBSCRIPTION_TODO_CATEGORY_LIMITS = {
  FREE: TODO_CATEGORY_LIMITS.FREE_MAX_COUNT,
  ACTIVE: null, // 무제한
  EXPIRED: TODO_CATEGORY_LIMITS.FREE_MAX_COUNT,
  CANCELLED: TODO_CATEGORY_LIMITS.FREE_MAX_COUNT,
} as const;
