export const AI_PARSE_LIMITS = {
  FREE_DAILY_LIMIT: 5,
} as const;

export const SUBSCRIPTION_AI_PARSE_LIMITS = {
  FREE: AI_PARSE_LIMITS.FREE_DAILY_LIMIT,
  ACTIVE: null, // 무제한
  EXPIRED: AI_PARSE_LIMITS.FREE_DAILY_LIMIT,
  CANCELLED: AI_PARSE_LIMITS.FREE_DAILY_LIMIT,
} as const;
