export const AI_PARSE_LIMITS = {
  FREE_DAILY_LIMIT: 5,
} as const;

export const SUBSCRIPTION_AI_PARSE_LIMITS = {
  FREE: AI_PARSE_LIMITS.FREE_DAILY_LIMIT,
  ACTIVE: null, // 무제한
  EXPIRED: AI_PARSE_LIMITS.FREE_DAILY_LIMIT,
  CANCELLED: AI_PARSE_LIMITS.FREE_DAILY_LIMIT,
} as const;

export const AI_REPORT_LIMITS = {
  WEEKLY_CRON_HOUR_UTC: 22,
  WEEKLY_CRON_DAY: 0,
  MONTHLY_CRON_HOUR_UTC: 22,
} as const;

export const AI_SUGGESTION_LIMITS = {
  MIN_OCCURRENCES: 3,
  ANALYSIS_WEEKS: 2,
  MAX_SUGGESTIONS_PER_USER: 5,
  SUGGESTION_EXPIRY_DAYS: 14,
  DEFAULT_RECURRING_WEEKS: 4,
} as const;
