export const TODO_LIMITS = {
  FREE_MAX_ACTIVE: 30,
} as const;

export const SUBSCRIPTION_TODO_LIMITS = {
  FREE: TODO_LIMITS.FREE_MAX_ACTIVE,
  ACTIVE: null, // 무제한
  EXPIRED: TODO_LIMITS.FREE_MAX_ACTIVE,
  CANCELLED: TODO_LIMITS.FREE_MAX_ACTIVE,
} as const;
