import type { Contract } from "../../../generated/prisma8/contract.d.js";
import type { DatabaseRecord } from "./database-records.js";

export type Account = DatabaseRecord<"Account">;
export type AiReport = DatabaseRecord<"AiReport">;
export type Cheer = DatabaseRecord<"Cheer">;
export type DailyCompletion = DatabaseRecord<"DailyCompletion">;
export type Follow = DatabaseRecord<"Follow">;
export type LoginAttempt = DatabaseRecord<"LoginAttempt">;
export type Memo = DatabaseRecord<"Memo">;
export type Notification = DatabaseRecord<"Notification">;
export type Nudge = DatabaseRecord<"Nudge">;
export type OAuthState = DatabaseRecord<"OAuthState">;
export type PushDailyBudget = DatabaseRecord<"PushDailyBudget">;
export type PushDeliveryAttempt = DatabaseRecord<"PushDeliveryAttempt">;
export type PushDispatch = DatabaseRecord<"PushDispatch">;
export type PushDispatchOutbox = DatabaseRecord<"PushDispatchOutbox">;
export type PushRateLimitReservation = DatabaseRecord<"PushRateLimitReservation">;
export type PushToken = DatabaseRecord<"PushToken">;
export type RecurringSuggestion = DatabaseRecord<"RecurringSuggestion">;
export type ReminderNudge = DatabaseRecord<"ReminderNudge">;
export type RetentionExperimentAssignment = DatabaseRecord<"RetentionExperimentAssignment">;
export type RetentionExperimentResult = DatabaseRecord<"RetentionExperimentResult">;
export type RetentionExperimentStage = DatabaseRecord<"RetentionExperimentStage">;
export type RetentionPushOutbox = DatabaseRecord<"RetentionPushOutbox">;
export type SecurityLog = DatabaseRecord<"SecurityLog">;
export type Session = DatabaseRecord<"Session">;
export type Subscription = DatabaseRecord<"Subscription">;
export type Todo = DatabaseRecord<"Todo">;
export type TodoCategory = DatabaseRecord<"TodoCategory">;
export type TodoComment = DatabaseRecord<"TodoComment">;
export type TodoCommentLike = DatabaseRecord<"TodoCommentLike">;
export type TodoItem = DatabaseRecord<"TodoItem">;
export type TodoView = DatabaseRecord<"TodoView">;
export type User = DatabaseRecord<"User">;
export type UserActivityDay = DatabaseRecord<"UserActivityDay">;
export type UserConsent = DatabaseRecord<"UserConsent">;
export type UserLocation = DatabaseRecord<"UserLocation">;
export type UserPreference = DatabaseRecord<"UserPreference">;
export type UserProfile = DatabaseRecord<"UserProfile">;
export type Verification = DatabaseRecord<"Verification">;
export type WeeklyAchievement = DatabaseRecord<"WeeklyAchievement">;

type NativeEnums = Contract["storage"]["namespaces"]["public"]["entries"]["valueSet"];
export type AccountProvider = NativeEnums["AccountProvider"]["values"][number];
export type FollowStatus = NativeEnums["FollowStatus"]["values"][number];
export type NotificationActionType = NativeEnums["NotificationActionType"]["values"][number];
export type NotificationPurpose = NativeEnums["NotificationPurpose"]["values"][number];
export type NotificationType = NativeEnums["NotificationType"]["values"][number];
export type NudgeReplyKind = NativeEnums["NudgeReplyKind"]["values"][number];
export type Platform = NativeEnums["Platform"]["values"][number];
export type PushDeliveryMode = NativeEnums["PushDeliveryMode"]["values"][number];
export type PushDeliveryStatus = NativeEnums["PushDeliveryStatus"]["values"][number];
export type PushDispatchOutboxStatus = NativeEnums["PushDispatchOutboxStatus"]["values"][number];
export type PushDispatchStatus = NativeEnums["PushDispatchStatus"]["values"][number];
export type PushRateLimitPhase = NativeEnums["PushRateLimitPhase"]["values"][number];
export type ReportType = NativeEnums["ReportType"]["values"][number];
export type RetentionExperimentStageName =
	NativeEnums["RetentionExperimentStageName"]["values"][number];
export type RetentionExperimentStageStatus =
	NativeEnums["RetentionExperimentStageStatus"]["values"][number];
export type RetentionExperimentVariant =
	NativeEnums["RetentionExperimentVariant"]["values"][number];
export type RetentionOutboxStatus = NativeEnums["RetentionOutboxStatus"]["values"][number];
export type SecurityEvent = NativeEnums["SecurityEvent"]["values"][number];
export type SubscriptionStatus = NativeEnums["SubscriptionStatus"]["values"][number];
export type SuggestionStatus = NativeEnums["SuggestionStatus"]["values"][number];
export type TimeFormat = NativeEnums["TimeFormat"]["values"][number];
export type TodoVisibility = NativeEnums["TodoVisibility"]["values"][number];
export type UserRole = NativeEnums["UserRole"]["values"][number];
export type UserStatus = NativeEnums["UserStatus"]["values"][number];
export type VerificationType = NativeEnums["VerificationType"]["values"][number];
