export const PASSWORD_RULES = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 72,
  /** 8자 이상, 영문과 숫자 필수 조합 */
  PATTERN: /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d@$!%*#?&]{8,}$/,
  ERROR_MESSAGE: '비밀번호는 8자 이상, 영문과 숫자를 포함해야 합니다',
} as const;

// Argon2id 해싱 설정 (OWASP 권장: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html)
export const ARGON2_CONFIG = {
  MEMORY_COST: 65536, // 64MB
  TIME_COST: 3,
  PARALLELISM: 4,
  HASH_LENGTH: 32,
} as const;

export const VERIFICATION_CODE = {
  LENGTH: 6,
  EXPIRY_MINUTES: 10,
  MAX_ATTEMPTS: 5,
  RESEND_COOLDOWN_SECONDS: 60,
} as const;

export const LOGIN_ATTEMPT = {
  MAX_FAILURES: 5,
  LOCKOUT_MINUTES: 15,
} as const;

export const JWT_CONFIG = {
  ACCESS_EXPIRES_IN: '15m',
  REFRESH_EXPIRES_IN: '7d',
} as const;

export const DEVICE_TYPES = ['IOS', 'ANDROID', 'WEB'] as const;
export type DeviceType = (typeof DEVICE_TYPES)[number];

export const USER_STATUS = ['ACTIVE', 'LOCKED', 'SUSPENDED', 'PENDING_VERIFY'] as const;
export type UserStatus = (typeof USER_STATUS)[number];

export const REVOKE_REASON = {
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  USER_REVOKE: 'USER_REVOKE',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

export type RevokeReason = (typeof REVOKE_REASON)[keyof typeof REVOKE_REASON];

export const SECURITY_EVENT = {
  REGISTRATION: 'REGISTRATION',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  TWO_FACTOR_ENABLED: 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED: 'TWO_FACTOR_DISABLED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_REVOKED_ALL: 'SESSION_REVOKED_ALL',
  OAUTH_LINKED: 'OAUTH_LINKED',
  OAUTH_UNLINKED: 'OAUTH_UNLINKED',
  OAUTH_AUTO_LINKED: 'OAUTH_AUTO_LINKED',
  OAUTH_LINK_REQUIRED: 'OAUTH_LINK_REQUIRED',
} as const;

export type SecurityEvent = (typeof SECURITY_EVENT)[keyof typeof SECURITY_EVENT];

export const VERIFICATION_TYPE = {
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

export type VerificationTypeValue = (typeof VERIFICATION_TYPE)[keyof typeof VERIFICATION_TYPE];
