const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * androidx.work 버전 정렬로 중복 클래스 빌드 실패를 방지합니다.
 *
 * react-native-android-widget이 `androidx.work:work-runtime:2.8.1`을 추가하고
 * (PR #148 — 위젯 갱신을 expedited work로 실행), 다른 의존성(expo-notifications 계열)이
 * 구버전 `work-runtime-ktx:2.7.1`을 전이시킵니다. 버전이 서로 다르면 ktx 클래스가
 * 양쪽에 존재해 `Duplicate class androidx.work.OneTimeWorkRequestKt` 등으로
 * checkDebugDuplicateClasses가 실패합니다.
 *
 * WorkManager 2.9.0부터 work-runtime-ktx는 빈 셔틀(코루틴 API가 work-runtime으로
 * 병합)이므로 2.9.1로 정렬하면 중복 클래스 카테고리 자체가 사라집니다.
 * 근거: https://developer.android.com/jetpack/androidx/releases/work (2.9.0 노트),
 * 동일 사례 https://github.com/OneSignal/OneSignal-Android-SDK/issues/1915
 */
const WORK_VERSION = '2.9.1';

const RESOLUTION_BLOCK = `
// @generated by withAndroidXWorkAlignment — androidx.work 중복 클래스 방지
configurations.all {
    resolutionStrategy {
        force "androidx.work:work-runtime:${WORK_VERSION}"
        force "androidx.work:work-runtime-ktx:${WORK_VERSION}"
    }
}
`;

const withAndroidXWorkAlignment = (config) => {
  return withAppBuildGradle(config, (gradleConfig) => {
    if (!gradleConfig.modResults.contents.includes('withAndroidXWorkAlignment')) {
      gradleConfig.modResults.contents += RESOLUTION_BLOCK;
    }
    return gradleConfig;
  });
};

module.exports = withAndroidXWorkAlignment;
