const { withFinalizedMod } = require('expo/config-plugins');
const { readFile, writeFile } = require('node:fs/promises');
const { join } = require('node:path');

const WIDGET_RESOURCES = [
  'aido_today_summary_info.xml',
  'aido_today_list_info.xml',
  'aido_today_large_info.xml',
];

// Widget XML files are generated by expo-widgets in its Android dangerous mod.
module.exports = (config) =>
  withFinalizedMod(config, [
    'android',
    async (androidConfig) => {
      const xmlDirectory = join(
        androidConfig.modRequest.platformProjectRoot,
        'app/src/main/res/xml',
      );

      for (const resource of WIDGET_RESOURCES) {
        const resourcePath = join(xmlDirectory, resource);
        const xml = await readFile(resourcePath, 'utf8');
        if (!/android:updatePeriodMillis="[0-9]+"/.test(xml)) {
          throw new Error(`expo-widgets refresh attribute missing in ${resource}`);
        }
        await writeFile(
          resourcePath,
          xml.replace(
            /android:updatePeriodMillis="[0-9]+"/,
            'android:updatePeriodMillis="1800000"',
          ),
        );
      }

      return androidConfig;
    },
  ]);
