export const FOLLOW_LIMITS = {
  FREE_MAX_FRIENDS: 5,
} as const;

export const SUBSCRIPTION_FOLLOW_LIMITS = {
  FREE: FOLLOW_LIMITS.FREE_MAX_FRIENDS,
  ACTIVE: null, // 무제한
  EXPIRED: FOLLOW_LIMITS.FREE_MAX_FRIENDS,
  CANCELLED: FOLLOW_LIMITS.FREE_MAX_FRIENDS,
} as const;
