import AppleIconSvg from '@assets/icons/ic_apple.svg';
import ArrowLeftIconSvg from '@assets/icons/ic_arrow_left.svg';
import ArrowRightIconSvg from '@assets/icons/ic_arrow_right.svg';
import BellIconSvg from '@assets/icons/ic_bell.svg';
import CheckIconSvg from '@assets/icons/ic_check.svg';
import CheckmarkIconSvg from '@assets/icons/ic_checkmark.svg';
import CopyIconSvg from '@assets/icons/ic_copy.svg';
import DeviceIconSvg from '@assets/icons/ic_device.svg';
import DocsIconSvg from '@assets/icons/ic_docs.svg';
import DragIconSvg from '@assets/icons/ic_drag.svg';
import EditIconSvg from '@assets/icons/ic_edit.svg';
import EyeIconSvg from '@assets/icons/ic_eye.svg';
import EyeOffIconSvg from '@assets/icons/ic_eye_off.svg';
import FishIconSvg from '@assets/icons/ic_fish.svg';
import GoogleIconSvg from '@assets/icons/ic_google.svg';
import KakaoIconSvg from '@assets/icons/ic_kakao.svg';
import LockIconSvg from '@assets/icons/ic_lock.svg';
import MenuIconSvg from '@assets/icons/ic_menu.svg';
import MicIconSvg from '@assets/icons/ic_mic.svg';
import MoonIconSvg from '@assets/icons/ic_moon.svg';
import MoreIconSvg from '@assets/icons/ic_more.svg';
import NaverIconSvg from '@assets/icons/ic_naver.svg';
import PauseIconSvg from '@assets/icons/ic_pause.svg';
import PawIconSvg from '@assets/icons/ic_paw.svg';
import PersonIconSvg from '@assets/icons/ic_person.svg';
import PlusIconSvg from '@assets/icons/ic_plus.svg';
import SearchIconSvg from '@assets/icons/ic_search.svg';
import SendIconSvg from '@assets/icons/ic_send.svg';
import SunIconSvg from '@assets/icons/ic_sun.svg';
import TrashIconSvg from '@assets/icons/ic_trash.svg';
import { createStyledIcon } from './createStyledIcon';

// 래핑된 아이콘 컴포넌트들
export const AppleIcon = createStyledIcon(AppleIconSvg);
export const ArrowLeftIcon = createStyledIcon(ArrowLeftIconSvg);
export const ArrowRightIcon = createStyledIcon(ArrowRightIconSvg);
export const BellIcon = createStyledIcon(BellIconSvg);
export const CheckIcon = createStyledIcon(CheckIconSvg);
export const CheckmarkIcon = createStyledIcon(CheckmarkIconSvg);
export const CopyIcon = createStyledIcon(CopyIconSvg);
export const DeviceIcon = createStyledIcon(DeviceIconSvg);
export const DocsIcon = createStyledIcon(DocsIconSvg);
export const DragIcon = createStyledIcon(DragIconSvg);
export const EditIcon = createStyledIcon(EditIconSvg);
export const FishIcon = createStyledIcon(FishIconSvg);
export const EyeIcon = createStyledIcon(EyeIconSvg);
export const EyeOffIcon = createStyledIcon(EyeOffIconSvg);
export const GoogleIcon = createStyledIcon(GoogleIconSvg);
export const KakaoIcon = createStyledIcon(KakaoIconSvg);
export const LockIcon = createStyledIcon(LockIconSvg);
export const MenuIcon = createStyledIcon(MenuIconSvg);
export const MoonIcon = createStyledIcon(MoonIconSvg);
export const MicIcon = createStyledIcon(MicIconSvg);
export const MoreIcon = createStyledIcon(MoreIconSvg);
export const NaverIcon = createStyledIcon(NaverIconSvg);
export const PawIcon = createStyledIcon(PawIconSvg);
export const PauseIcon = createStyledIcon(PauseIconSvg);
export const PersonIcon = createStyledIcon(PersonIconSvg);
export const PlusIcon = createStyledIcon(PlusIconSvg);
export const SearchIcon = createStyledIcon(SearchIconSvg);
export const SendIcon = createStyledIcon(SendIconSvg);
export const SunIcon = createStyledIcon(SunIconSvg);
export const TrashIcon = createStyledIcon(TrashIconSvg);
