import AppleIconSvg from '@assets/icons/ic_apple.svg';
import ArrowLeftIconSvg from '@assets/icons/ic_arrow_left.svg';
import ArrowRightIconSvg from '@assets/icons/ic_arrow_right.svg';
import BellIconSvg from '@assets/icons/ic_bell.svg';
import CheckIconSvg from '@assets/icons/ic_check.svg';
import DocsIconSvg from '@assets/icons/ic_docs.svg';
import GoogleIconSvg from '@assets/icons/ic_google.svg';
import KakaoIconSvg from '@assets/icons/ic_kakao.svg';
import LockIconSvg from '@assets/icons/ic_lock.svg';
import MenuIconSvg from '@assets/icons/ic_menu.svg';
import MicIconSvg from '@assets/icons/ic_mic.svg';
import NaverIconSvg from '@assets/icons/ic_naver.svg';
import PersonIconSvg from '@assets/icons/ic_person.svg';
import PlusIconSvg from '@assets/icons/ic_plus.svg';
import SearchIconSvg from '@assets/icons/ic_search.svg';
import SendIconSvg from '@assets/icons/ic_send.svg';
import { createStyledIcon } from './createStyledIcon';

// 래핑된 아이콘 컴포넌트들
export const AppleIcon = createStyledIcon(AppleIconSvg);
export const ArrowLeftIcon = createStyledIcon(ArrowLeftIconSvg);
export const ArrowRightIcon = createStyledIcon(ArrowRightIconSvg);
export const BellIcon = createStyledIcon(BellIconSvg);
export const CheckIcon = createStyledIcon(CheckIconSvg);
export const DocsIcon = createStyledIcon(DocsIconSvg);
export const GoogleIcon = createStyledIcon(GoogleIconSvg);
export const KakaoIcon = createStyledIcon(KakaoIconSvg);
export const LockIcon = createStyledIcon(LockIconSvg);
export const MenuIcon = createStyledIcon(MenuIconSvg);
export const MicIcon = createStyledIcon(MicIconSvg);
export const NaverIcon = createStyledIcon(NaverIconSvg);
export const PersonIcon = createStyledIcon(PersonIconSvg);
export const PlusIcon = createStyledIcon(PlusIconSvg);
export const SearchIcon = createStyledIcon(SearchIconSvg);
export const SendIcon = createStyledIcon(SendIconSvg);
