import AppleIconSvg from '@assets/icons/ic_apple.svg';
import ArrowLeftIconSvg from '@assets/icons/ic_arrow_left.svg';
import ArrowRightIconSvg from '@assets/icons/ic_arrow_right.svg';
import ArrowUpIconSvg from '@assets/icons/ic_arrow_up.svg';
import BellIconSvg from '@assets/icons/ic_bell.svg';
import CalendarIconSvg from '@assets/icons/ic_calendar.svg';
import CheckIconSvg from '@assets/icons/ic_check.svg';
import CheckmarkIconSvg from '@assets/icons/ic_checkmark.svg';
import ClockIconSvg from '@assets/icons/ic_clock.svg';
import CloseIconSvg from '@assets/icons/ic_close.svg';
import CopyIconSvg from '@assets/icons/ic_copy.svg';
import CrownIconSvg from '@assets/icons/ic_crown.svg';
import DeviceIconSvg from '@assets/icons/ic_device.svg';
import DocsIconSvg from '@assets/icons/ic_docs.svg';
import DragIconSvg from '@assets/icons/ic_drag.svg';
import EyeIconSvg from '@assets/icons/ic_eye.svg';
import EyeOffIconSvg from '@assets/icons/ic_eye_off.svg';
import FillCheckIconSvg from '@assets/icons/ic_fill_check.svg';
import FishIconSvg from '@assets/icons/ic_fish.svg';
import GoogleIconSvg from '@assets/icons/ic_google.svg';
import InfoIconSvg from '@assets/icons/ic_info.svg';
import KakaoIconSvg from '@assets/icons/ic_kakao.svg';
import ListIconSvg from '@assets/icons/ic_list.svg';
import LockIconSvg from '@assets/icons/ic_lock.svg';
import MenuIconSvg from '@assets/icons/ic_menu.svg';
import MicIconSvg from '@assets/icons/ic_mic.svg';
import MoonIconSvg from '@assets/icons/ic_moon.svg';
import MoreIconSvg from '@assets/icons/ic_more.svg';
import NaverIconSvg from '@assets/icons/ic_naver.svg';
import NotiIconSvg from '@assets/icons/ic_noti.svg';
import PauseIconSvg from '@assets/icons/ic_pause.svg';
import PawIconSvg from '@assets/icons/ic_paw.svg';
import PenIconSvg from '@assets/icons/ic_pen.svg';
import PersonIconSvg from '@assets/icons/ic_person.svg';
import PlusIconSvg from '@assets/icons/ic_plus.svg';
import SearchIconSvg from '@assets/icons/ic_search.svg';
import SendIconSvg from '@assets/icons/ic_send.svg';
import SunIconSvg from '@assets/icons/ic_sun.svg';
import ToastErrorIconSvg from '@assets/icons/ic_toast_error.svg';
import ToastSuccessIconSvg from '@assets/icons/ic_toast_success.svg';
import ToastWarningIconSvg from '@assets/icons/ic_toast_warning.svg';
import TrashIconSvg from '@assets/icons/ic_trash.svg';
import { createStyledIcon } from './createStyledIcon';

// 래핑된 아이콘 컴포넌트들
export const AppleIcon = createStyledIcon(AppleIconSvg);
export const ArrowLeftIcon = createStyledIcon(ArrowLeftIconSvg);
export const ArrowRightIcon = createStyledIcon(ArrowRightIconSvg);
export const ArrowUpIcon = createStyledIcon(ArrowUpIconSvg);
export const BellIcon = createStyledIcon(BellIconSvg);
export const CalendarIcon = createStyledIcon(CalendarIconSvg);
export const CheckIcon = createStyledIcon(CheckIconSvg);
export const CheckmarkIcon = createStyledIcon(CheckmarkIconSvg);
export const ClockIcon = createStyledIcon(ClockIconSvg);
export const CloseIcon = createStyledIcon(CloseIconSvg);
export const CopyIcon = createStyledIcon(CopyIconSvg);
export const CrownIcon = createStyledIcon(CrownIconSvg);
export const DeviceIcon = createStyledIcon(DeviceIconSvg);
export const DocsIcon = createStyledIcon(DocsIconSvg);
export const DragIcon = createStyledIcon(DragIconSvg);
export const EditIcon = createStyledIcon(PenIconSvg);
export const FillCheckIcon = createStyledIcon(FillCheckIconSvg);
export const FishIcon = createStyledIcon(FishIconSvg);
export const EyeIcon = createStyledIcon(EyeIconSvg);
export const EyeOffIcon = createStyledIcon(EyeOffIconSvg);
export const GoogleIcon = createStyledIcon(GoogleIconSvg);
export const InfoIcon = createStyledIcon(InfoIconSvg);
export const KakaoIcon = createStyledIcon(KakaoIconSvg);
export const ListIcon = createStyledIcon(ListIconSvg);
export const LockIcon = createStyledIcon(LockIconSvg);
export const MenuIcon = createStyledIcon(MenuIconSvg);
export const MoonIcon = createStyledIcon(MoonIconSvg);
export const MicIcon = createStyledIcon(MicIconSvg);
export const MoreIcon = createStyledIcon(MoreIconSvg);
export const NaverIcon = createStyledIcon(NaverIconSvg);
export const NotiIcon = createStyledIcon(NotiIconSvg);
export const PawIcon = createStyledIcon(PawIconSvg);
export const PauseIcon = createStyledIcon(PauseIconSvg);
export const PersonIcon = createStyledIcon(PersonIconSvg);
export const PlusIcon = createStyledIcon(PlusIconSvg);
export const SearchIcon = createStyledIcon(SearchIconSvg);
export const SendIcon = createStyledIcon(SendIconSvg);
export const SunIcon = createStyledIcon(SunIconSvg);
export const ToastErrorIcon = createStyledIcon(ToastErrorIconSvg);
export const ToastSuccessIcon = createStyledIcon(ToastSuccessIconSvg);
export const ToastWarningIcon = createStyledIcon(ToastWarningIconSvg);
export const TrashIcon = createStyledIcon(TrashIconSvg);
